#!/usr/bin/env bash

BE='bundle exec'
RU='rvm'

RVM_ENVIR=/etc/profile.d/rvm.sh
RUBY_VERS=2.6.2

   API="https://www.beeminder.com/api/v1"
  JSON="goals/ob-mirror/datapoints.json"
  TOKEN="auth_token=${AUTH_TOKEN}"

curl -s "$API/users/yebyenw/$JSON?$TOKEN" > ob-mirror.json

 .  $RVM_ENVIR
$RU $RUBY_VERS
$BE ./obgraph.rb
